# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#
source = ~/.config/hypr/hyprpaper.conf
$font = JetBrainsMono Nerd Font
general {
    hide_cursor = true
}
animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}
background {
    monitor =
    path = $BG1
    blur_passes = 1
}
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 6
    inner_color = rgba(0, 0, 0, 0.0) # no fill
    outer_color = rgb(7fb4ca) #45deg
    font_color = rgb(e6c384)
    fade_on_empty = false
    rounding = 15
    font_family = $font
    placeholder_text = <span size='18pt' weight='bold'>[  ]</span>
    fail_text = $PAMFAIL
    dots_size = 0.20
    dots_spacing = 0.3
    position = 0, -20
    halign = center
    valign = center
}
