# Set true color
set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty*:RGB"

# Set binding
unbind C-b
set -g prefix C-space
bind C-space send-prefix

# Set Window Index Start at 1 
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# scrollback buffer
set -g history-limit 10000

# bar
set -g status-style bg=default
set -g status-right ""

# vim key bindings
set -g mode-keys vi
set -g status-keys vi

# clipboard
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy && wl-paste -n | wl-copy -p"
bind-key p run "wl-paste -n | tmux load-buffer - ; tmux paste-buffer"
